# Generated by Django 5.0.6 on 2024-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingroom",
            name="available",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="booked_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="number_of_people",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
